FROM golang:1.20-alpine

ADD . /app/testTask

WORKDIR /testTask

COPY . ./

RUN go mod download

#RUN go build -o ./cmd/bin/server/server ./server && go build -o ./cmd/bin/client/client ./client
####################### not finished